project_name: dnstrace
builds:
  -
    binary: dnstrace
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
git:
  short_hash: true
nfpm:
  maintainer: Olivier Poitrey <rs@rhapsodyk.net>
  description: DNS resolution tracing tool
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
